spring.application.name=GestionPae
spring.datasource.url=jdbc:postgresql://ep-shy-wildflower-a4py6yee-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mcvVWDnoO9j1
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.jpa.hibernate.ddl-auto=update

